name: Check Changelog

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

permissions:
  contents: read

jobs:
  check-changelog:
    runs-on: pub-hk-ubuntu-22.04-small # TODO: change to ubuntu-latest once repo is public
    if: (!contains(github.event.pull_request.labels.*.name, 'skip changelog'))
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check that CHANGELOG is touched
        run: |
          git fetch origin ${{ github.base_ref }} --depth 1 && \
          git diff remotes/origin/${{ github.base_ref }} --name-only | grep CHANGELOG.md
